function [T1,T2]=Mex3DTauIso(c,Check_f,T1,T2,omw,NN_aVw1,NN_aVw2,...
    Cheq1P_Xm,Cheq1P_Xp,Cheq1P_Ym,Cheq1P_Yp,Cheq1P_Zm,Cheq1P_Zp,...
    Cheq2P_Xm,Cheq2P_Xp,Cheq2P_Ym,Cheq2P_Yp,Cheq2P_Zm,Cheq2P_Zp) %#codegen

if c>1 %3D
    for i=1:Check_f
        T1(1:end-2)=omw*T1(1:end-2)+NN_aVw1.*(...
            T2(Cheq1P_Xm)+T2(Cheq1P_Xp)+...
            T2(Cheq1P_Ym)+T2(Cheq1P_Yp)+...
            T2(Cheq1P_Zm)+T2(Cheq1P_Zp));
        T2(1:end-2)=omw*T2(1:end-2)+NN_aVw2.*(...
            T1(Cheq2P_Xm)+T1(Cheq2P_Xp)+...
            T1(Cheq2P_Ym)+T1(Cheq2P_Yp)+...
            T1(Cheq2P_Zm)+T1(Cheq2P_Zp));
    end
else %2D
    for i=1:Check_f
        T1(1:end-2)=omw*T1(1:end-2)+NN_aVw1.*(...
            T2(Cheq1P_Xm)+T2(Cheq1P_Xp)+...
            T2(Cheq1P_Ym)+T2(Cheq1P_Yp));
        T2(1:end-2)=omw*T2(1:end-2)+NN_aVw2.*(...
            T1(Cheq2P_Xm)+T1(Cheq2P_Xp)+...
            T1(Cheq2P_Ym)+T1(Cheq2P_Yp));
    end
end